### ISSUE TITLE
Registrering `MCMCDiagnostics.jl`?

### ISSUE THREAD

**Issue by Sleort** [tpapp/MCMCDiagnostics.jl#1]
It would be nice if `MCMCDiagnostics.jl` could be registrered.

(The name should then maybe be changed to something like `MarkovChainMonteCarloDiagnostics.jl`, given the discussion [here](https://discourse.julialang.org/t/package-naming-guidelines/7140)?)

**Comment by tpapp** [comment]
Started registration after you asked, but it is still pending, I guess they will be reviewed at some point:
https://github.com/JuliaLang/METADATA.jl/pull/12307

**Comment by Sleort** [comment]
Yeah, I've seen that... Thanks a lot! I'm looking forward to the registration going through.

**Comment by Sleort** [comment]
The registration has finally gone through, so I'll close the issue. Again, thanks for sharing!
